config/routes.rb
Picsite::Application.routes.draw do
  root to: 'homepage#index'
  
  resources :users, only: [:show]
  get    'join' => 'users#new'
  post   'join' => 'users#create'
  get    'settings' => 'users#edit'
  put    'settings' => 'users#update'
    
  get    'changepassword' => 'changepassword#edit',   path: '/settings/changepassword'
  put    'changepassword' => 'changepassword#update', path: '/settings/changepassword'
  
  get    'delete_user' => 'delete_user#edit',    path: '/settings/delete'
  delete 'delete_user' => 'delete_user#destroy', path: '/settings/delete'
  
  get    'user_sessions' => 'sessions#index',   path: '/settings/sessions'
  delete 'user_session'  => 'sessions#destroy', path: '/settings/sessions/:id'
  
  get    'signin'  => 'sessions#new'
  post   'signin'  => 'sessions#create'
  match  'signout' => 'sessions#update'
  
  get    'forgotpassword' => 'forgotpassword#edit'
  match  'forgotpassword' => 'forgotpassword#update', via: [:post, :put]
  
  get    'resetpassword' => 'resetpassword#edit',   path: '/resetpassword/:token'
  put    'resetpassword' => 'resetpassword#update', path: '/resetpassword/:token'
  
  namespace :admin do
    root to: 'homepage#index'
    resources :users, only: [:index, :edit, :update] do
      resources :sessions, only: [:index, :destroy]
    end
  end
end

app/models/user.rb
class User < ActiveRecord::Base
  attr_accessor :remember
  attr_readonly :id, :username, :display_name, :created_at
  attr_accessible :username, :email, :password, :password_confirmation, as: :join
  attr_accessible :email, :status, as: :admin
  
  has_many :sessions, class_name: 'UserSession'
  
  after_validation :clear_password_digest_errors
  before_create :set_display_and_username
  
  has_secure_password
  validates :username, presence: true, length: { minimum: 3, maximum: 30, allow_blank: true }, format: { with: /^[a-zA-Z0-9\-_]+$/, allow_blank: true }, uniqueness: { case_sensitive: false, if: "errors[:username].empty?" }
  validates :status, inclusion: { in: ['active', 'deleted', 'banned', 'admin'] }
  validates :email, length: { maximum: 100 }, format: { with: /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i, allow_blank: true }
  validates :password, presence: true, length: { minimum: 6, allow_blank: true }, if: :password_required?
  
  def to_param
    display_name
  end
  
  def self.active
    where(status: ['active', 'admin'])
  end
  
  def self.admin
    where(status: 'admin')
  end
  
  def self.get_by_username(username)
    active.find_by_username(username.downcase) if username
  end
  
  def self.admin_get_by_username(username)
    find_by_username(username.downcase) if username
  end
  
  def self.get_by_token(token)
    active.find_by_forgot_password_token(token) if token
  end
  
  def change_email(unencrypted_password, params)
    if params[:email]
      self.email = params[:email]
      if authenticate_change(unencrypted_password)
        save
      else
        false
      end
    else
      errors.add(:base, 'Error updating email')
      false
    end
  end
  
  def change_password(unencrypted_password, params)
    if authenticate_change(unencrypted_password)
      update_password(params)
    end
  end
  
  def delete_user(unencrypted_password)
    if authenticate_change(unencrypted_password)
      self.status = 'deleted'
      save
    end
  end
  
  def self.signin(params)
    user = get_by_username(params[:username])
    user if user && params[:password] && user.authenticate(params[:password])
  end
  
  def self.forgot_password(params)
    user = get_by_username(params[:username])
    if user
      if not user.email.blank?
        user.forgot_password_token = user.id.to_s+'-'+Digest::SHA1.hexdigest(Time.now.to_s)
        user.forgot_password_at = Time.now
        user.save
      else
        user.errors.add(:base, 'No email is linked to this username')
      end
    else
      user = User.new
      user.username = params[:username]
      user.errors.add(:username, 'not found')
    end
    user
  end
  
  def self.reset_password(token, params)
    user = get_by_token(token)
    user.update_password(params) if user
    user
  end
  
  def update_password(params)
    self.password = params[:password] || ''
    self.password_confirmation = params[:password_confirmation] || ''
    self.forgot_password_token = nil
    self.forgot_password_at = nil
    save
  end
  
  private
  
  def set_display_and_username
    if username
      self.display_name = username
      self.username = username.downcase
    end
  end
  
  def clear_password_digest_errors
    errors[:password_digest].clear if errors[:password].any?
  end
  
  def password_required?
    new_record? or password
  end
  
  def authenticate_change(unencrypted_password)
    if authenticate(unencrypted_password)
      true
    else
      errors.add(:base, 'Password is incorrect')
      false
    end
  end
end

app/controllers/admin/users_controller.rb
class Admin::UsersController < Admin::ApplicationController
  def index
    @users = User.all
  end
  
  def edit
    @user = User.admin_get_by_username(params[:id])
  end
  
  def update
    @user = User.admin_get_by_username(params[:id])
    if @user.update_attributes(params[:user], as: :admin)
      redirect_to edit_admin_user_path(@user), notice: 'Update Successful.'
    else
      render :edit
    end
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_filter :signin_required, only: [:edit, :update, :destroy]
  
  def new
    @user = User.new
  end

  def create
    @user = User.new(params[:user], as: :join)
    if @user.save
      signin(@user)
      redirect_to root_path, notice: 'Thank You for joining PicSite.'
    else
      render :new
    end
  end
  
  def show
    @user = User.get_by_username(params[:id])
    render_error(404) and return if !@user
  end
  
  def edit
  end
  
  def update
    @current_user.change_email(params[:password], params[:user])
    render :edit
  end
end

app/helpers/admin/users_helper.rb
module Admin::UsersHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/_settings_menu.html.erb
<div class="col-sm">
	<div class="panel panel-nav">
		<div class="panel-heading"><h3 class="panel-title">Settings</h3></div>
		<div class="panel-nav-body">
			<a href="<%= settings_path       %>" class="panel-nav-item<%= ' active' if active_page == 'basic'    %>">Basic Settings</a>
			<a href="<%= changepassword_path %>" class="panel-nav-item<%= ' active' if active_page == 'password' %>">Change Password</a>
			<a href="<%= user_sessions_path  %>" class="panel-nav-item<%= ' active' if active_page == 'sessions' %>">Session History</a>
			<a href="<%= delete_user_path    %>" class="panel-nav-item<%= ' active' if active_page == 'delete'   %>">Delete Account</a>
		</div>
	</div>
</div>
<div class="col-lg">
	<%= yield %>
</div>
<script>
(function($) {
	$('.panel-nav .panel-heading').on('click', function() {
		$(this).parent().find('.panel-nav-body').toggleClass('in');
	});
})(jQuery);
</script>

app/views/users/edit.html.erb
<%= render layout: 'settings_menu', locals: { active_page: 'basic' } do %>
	<div class="panel">
		<div class="panel-heading"><h3 class="panel-title">Basic Settings</h3></div>
		<div class="panel-body">
			<%= form_for @current_user, url: settings_path, html: { id: nil, class: nil } do |f| %>
				<div class="alert alert-danger<%= ' hide' if @current_user.errors.empty? %>" role="alert"><%= @current_user.errors.full_messages.join('<br>').html_safe %></div>
				<div class="form-group">
					<label class="control-label" for="email">Email Address (optional):</label>
					<input type="text" id="email" class="form-control" name="user[email]" value="<%= @current_user.email %>" autofocus>
				</div>
				<div class="form-group">
					<label class="control-label" for="password">Current Password:</label>
					<input type="password" id="password" class="form-control" name="password">
					<p class="help-block">To save your changes, please enter your password.</p>
				</div>
				<button type="submit" class="btn">Save Changes</button>
			<% end %>
		</div>
	</div>
<% end %>

app/views/users/new.html.erb
<div class="col-md col-center">
	<div class="panel">
		<div class="panel-heading"><h3 class="panel-title">Join PicSite</h3></div>
		<div class="panel-body">
			<%= form_for @user, url: join_path, html: { id: nil, class: 'join-form' } do |f| %>
				<div class="alert alert-danger<%= ' hide' if @user.errors.empty? %>" role="alert"><%= @user.errors.full_messages.join('<br>').html_safe %></div>
				<div class="form-group<% if @user.errors[:username].any? %> has-error<% end %>">
					<label class="control-label" for="username">Username:</label>
					<input type="text" id="username" class="form-control" name="user[username]" value="<%= params[:user] ? params[:user][:username] : '' %>" autofocus>
				</div>
				<div class="form-group<% if @user.errors[:email].any? %> has-error<% end %>">
					<label class="control-label" for="email">Email Address (optional):</label>
					<input type="text" id="email" class="form-control" name="user[email]" value="<%= params[:user] ? params[:user][:email] : '' %>">
				</div>
				<div class="form-group<% if @user.errors[:password].any? %> has-error<% end %>">
					<label class="control-label" for="password">Password:</label>
					<input type="password" id="password" class="form-control" name="user[password]">
				</div>
				<div class="form-group<% if @user.errors[:password_confirmation].any? %> has-error<% end %>">
					<label class="control-label" for="password_confirmation">Confirm Your Password:</label>
					<input type="password" id="password_confirmation" class="form-control" name="user[password_confirmation]">
				</div>
				<button type="submit" class="btn btn-block">Join</button>
				<p class="help-block">Joining means you accept our <a href="#">Terms of Use</a> and <a href="#">Privacy Policy</a>.</p>
			<% end %>
		</div>
		<div class="panel-footer">
			<h4 class="text-center">Already have an account?<br><a href="<%= signin_path %>">Click&nbsp;here</a> to sign in.</h4>
		</div>
	</div>
</div>

app/views/users/show.html.erb
<div class="panel">
	<div class="panel-body">
		<h1><%= @user.display_name %></h1>
		<p>A member for <strong><%= time_ago_in_words(@user.created_at) %></strong></p>
	</div>
</div>