config/routes.rb
Picsite::Application.routes.draw do
  root to: 'homepage#index'
  
  resources :users, only: [:show]
  get    'join' => 'users#new'
  post   'join' => 'users#create'
  get    'settings' => 'users#edit'
  put    'settings' => 'users#update'
    
  get    'changepassword' => 'changepassword#edit',   path: '/settings/changepassword'
  put    'changepassword' => 'changepassword#update', path: '/settings/changepassword'
  
  get    'delete_user' => 'delete_user#edit',    path: '/settings/delete'
  delete 'delete_user' => 'delete_user#destroy', path: '/settings/delete'
  
  get    'user_sessions' => 'sessions#index',   path: '/settings/sessions'
  delete 'user_session'  => 'sessions#destroy', path: '/settings/sessions/:id'
  
  get    'signin'  => 'sessions#new'
  post   'signin'  => 'sessions#create'
  match  'signout' => 'sessions#update'
  
  get    'forgotpassword' => 'forgotpassword#edit'
  match  'forgotpassword' => 'forgotpassword#update', via: [:post, :put]
  
  get    'resetpassword' => 'resetpassword#edit',   path: '/resetpassword/:token'
  put    'resetpassword' => 'resetpassword#update', path: '/resetpassword/:token'
  
  namespace :admin do
    root to: 'homepage#index'
    resources :users, only: [:index, :edit, :update] do
      resources :sessions, only: [:index, :destroy]
    end
  end
end

app/controllers/forgotpassword_controller.rb
class ForgotpasswordController < ApplicationController
  def edit
    @user = User.new
  end

  def update
    @user = User.forgot_password(params[:user])
    if @user.errors.empty?
      ForgotpasswordMailer.forgotpassword_email(@user).deliver
      @message = 'An Email has been sent to reset the password.'
    end
    render :edit
  end
end

app/helpers/forgotpassword_helper.rb
module ForgotpasswordHelper
end

app/views/forgotpassword/edit.html.erb
<div class="col-md col-center">
	<div class="panel">
		<div class="panel-heading">
			<h3 class="panel-title">Forgot Password</h3>
			<h5>Enter your Username and we will email you a link to reset your Password.</h5>
		</div>
		<div class="panel-body">
			<%= form_for @user, url: forgotpassword_path, html: { id: nil, class: nil } do |f| %>
				<div class="alert alert-danger<%= ' hide' if @user.errors.empty? %>" role="alert"><%= @user.errors.full_messages.join('<br>').html_safe %></div>
				<div class="alert alert-info<%= ' hide' if @message.nil? %>"><%= @message %></div>
				<div class="form-group<% if not @user.errors[:username].empty? %> has-error<% end %>">
					<label for="username">Your Username:</label>
					<input type="text" id="username" class="form-control" name="user[username]" value="<%= params[:user] ? params[:user][:username] : '' %>">
				</div>
				<button type="submit" class="btn btn-block">Email Me</button>
			<% end %>
		</div>
	</div>
</div>