config/routes.rb
Picsite::Application.routes.draw do
  root to: 'homepage#index'
  
  resources :users, only: [:show]
  get    'join' => 'users#new'
  post   'join' => 'users#create'
  get    'settings' => 'users#edit'
  put    'settings' => 'users#update'
    
  get    'changepassword' => 'changepassword#edit',   path: '/settings/changepassword'
  put    'changepassword' => 'changepassword#update', path: '/settings/changepassword'
  
  get    'delete_user' => 'delete_user#edit',    path: '/settings/delete'
  delete 'delete_user' => 'delete_user#destroy', path: '/settings/delete'
  
  get    'user_sessions' => 'sessions#index',   path: '/settings/sessions'
  delete 'user_session'  => 'sessions#destroy', path: '/settings/sessions/:id'
  
  get    'signin'  => 'sessions#new'
  post   'signin'  => 'sessions#create'
  match  'signout' => 'sessions#update'
  
  get    'forgotpassword' => 'forgotpassword#edit'
  match  'forgotpassword' => 'forgotpassword#update', via: [:post, :put]
  
  get    'resetpassword' => 'resetpassword#edit',   path: '/resetpassword/:token'
  put    'resetpassword' => 'resetpassword#update', path: '/resetpassword/:token'
  
  namespace :admin do
    root to: 'homepage#index'
    resources :users, only: [:index, :edit, :update] do
      resources :sessions, only: [:index, :destroy]
    end
  end
end

app/models/user.rb
class User < ActiveRecord::Base
  attr_accessor :remember
  attr_readonly :id, :username, :display_name, :created_at
  attr_accessible :username, :email, :password, :password_confirmation, as: :join
  attr_accessible :email, :status, as: :admin
  
  has_many :sessions, class_name: 'UserSession'
  
  after_validation :clear_password_digest_errors
  before_create :set_display_and_username
  
  has_secure_password
  validates :username, presence: true, length: { minimum: 3, maximum: 30, allow_blank: true }, format: { with: /^[a-zA-Z0-9\-_]+$/, allow_blank: true }, uniqueness: { case_sensitive: false, if: "errors[:username].empty?" }
  validates :status, inclusion: { in: ['active', 'deleted', 'banned', 'admin'] }
  validates :email, length: { maximum: 100 }, format: { with: /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i, allow_blank: true }
  validates :password, presence: true, length: { minimum: 6, allow_blank: true }, if: :password_required?
  
  def to_param
    display_name
  end
  
  def self.active
    where(status: ['active', 'admin'])
  end
  
  def self.admin
    where(status: 'admin')
  end
  
  def self.get_by_username(username)
    active.find_by_username(username.downcase) if username
  end
  
  def self.admin_get_by_username(username)
    find_by_username(username.downcase) if username
  end
  
  def self.get_by_token(token)
    active.find_by_forgot_password_token(token) if token
  end
  
  def change_email(unencrypted_password, params)
    if params[:email]
      self.email = params[:email]
      if authenticate_change(unencrypted_password)
        save
      else
        false
      end
    else
      errors.add(:base, 'Error updating email')
      false
    end
  end
  
  def change_password(unencrypted_password, params)
    if authenticate_change(unencrypted_password)
      update_password(params)
    end
  end
  
  def delete_user(unencrypted_password)
    if authenticate_change(unencrypted_password)
      self.status = 'deleted'
      save
    end
  end
  
  def self.signin(params)
    user = get_by_username(params[:username])
    user if user && params[:password] && user.authenticate(params[:password])
  end
  
  def self.forgot_password(params)
    user = get_by_username(params[:username])
    if user
      if not user.email.blank?
        user.forgot_password_token = user.id.to_s+'-'+Digest::SHA1.hexdigest(Time.now.to_s)
        user.forgot_password_at = Time.now
        user.save
      else
        user.errors.add(:base, 'No email is linked to this username')
      end
    else
      user = User.new
      user.username = params[:username]
      user.errors.add(:username, 'not found')
    end
    user
  end
  
  def self.reset_password(token, params)
    user = get_by_token(token)
    user.update_password(params) if user
    user
  end
  
  def update_password(params)
    self.password = params[:password] || ''
    self.password_confirmation = params[:password_confirmation] || ''
    self.forgot_password_token = nil
    self.forgot_password_at = nil
    save
  end
  
  private
  
  def set_display_and_username
    if username
      self.display_name = username
      self.username = username.downcase
    end
  end
  
  def clear_password_digest_errors
    errors[:password_digest].clear if errors[:password].any?
  end
  
  def password_required?
    new_record? or password
  end
  
  def authenticate_change(unencrypted_password)
    if authenticate(unencrypted_password)
      true
    else
      errors.add(:base, 'Password is incorrect')
      false
    end
  end
end

app/controllers/admin/users_controller.rb
class Admin::UsersController < Admin::ApplicationController
  def index
    @users = User.all
  end
  
  def edit
    @user = User.admin_get_by_username(params[:id])
  end
  
  def update
    @user = User.admin_get_by_username(params[:id])
    if @user.update_attributes(params[:user], as: :admin)
      redirect_to edit_admin_user_path(@user), notice: 'Update Successful.'
    else
      render :edit
    end
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_filter :signin_required, only: [:edit, :update, :destroy]
  
  def new
    @user = User.new
  end

  def create
    @user = User.new(params[:user], as: :join)
    if @user.save
      signin(@user)
      redirect_to root_path, notice: 'Thank You for joining PicSite.'
    else
      render :new
    end
  end
  
  def show
    @user = User.get_by_username(params[:id])
    render_error(404) and return if !@user
  end
  
  def edit
  end
  
  def update
    @current_user.change_email(params[:password], params[:user])
    render :edit
  end
end

app/helpers/admin/users_helper.rb
module Admin::UsersHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/admin/users/_user_menu.html.erb
<div class="row">
	<div class="col-md-3">
		<div class="list-group">
			<a href="<%= admin_users_path %>" class="list-group-item">&lt; Back to Users List</a>
			<a href="<%= edit_admin_user_path(@user) %>" class="list-group-item<%= ' active' if controller.controller_name == 'users' %>">User Settings</a>
			<a href="<%= admin_user_sessions_path(@user) %>" class="list-group-item<%= ' active' if controller.controller_name == 'sessions' %>">User Sessions</a>
		</div>
	</div>
	<div class="col-md-9">
		<%= yield %>
	</div>
</div>

app/views/admin/users/edit.html.erb
<%= render layout: 'user_menu' do %>
	<div class="panel panel-default">
		<div class="panel-heading"><h3 class="text-center">Edit: <strong><%= @user.display_name %></strong></h3></div>
		<div class="panel-body">
			<p><strong>Joined:</strong> <%= time_ago_in_words(@user.created_at) %> ago (<%= @user.created_at %>)</p>
			<p><strong>Last Updated:</strong> <%= time_ago_in_words(@user.updated_at) %> ago (<%= @user.updated_at %>)</p>
			<hr>
			<%= form_for @user, url: admin_user_path(@user), html: { id: nil, class: nil } do |f| %>
				<div class="alert alert-danger<%= ' hide' if @user.errors.empty? %>" role="alert"><%= @user.errors.full_messages.join('<br>').html_safe %></div>
				<div class="form-group">
					<label class="control-label" for="email">Status:</label>
					<div class="radio">
						<label class="radio-inline">
							<input type="radio" name="user[status]" value="active"<%= ' checked' if @user.status =='active' %>> <span class="<%= 'strong' if @user.status == 'active' %>">Active</span>
						</label>
						<label class="radio-inline">
							<input type="radio" name="user[status]" value="deleted"<%= ' checked' if @user.status =='deleted' %>> <span class="<%= 'strong' if @user.status == 'deleted' %>">Deleted</span>
						</label>
						<label class="radio-inline">
 								<input type="radio" name="user[status]" value="banned"<%= ' checked' if @user.status =='banned' %>> <span class="<%= 'strong' if @user.status == 'banned' %>">Banned</span>
						</label>
						<label class="radio-inline">
 								<input type="radio" name="user[status]" value="admin"<%= ' checked' if @user.status =='admin' %>> <span class="<%= 'strong' if @user.status == 'admin' %>">Admin</span>
						</label>
					</div>
				</div>
				<div class="form-group">
					<label class="control-label" for="email">Email Address (optional):</label>
					<input type="text" id="email" class="form-control" name="user[email]" value="<%= @user.email %>">
				</div>
				<button type="submit" class="btn btn-primary">Save Changes</button>
			<% end %>
			<% if @user.forgot_password_token %>
			<hr>
			<div class="panel panel-info">
				<div class="panel-heading"><h3 class="panel-title">Reset Password Link:</h3></div>
				<div class="panel-body">
					<p><strong>Reset Password URL:</strong> <a href="<%= resetpassword_url(@user.forgot_password_token) %>"><%= resetpassword_url(@user.forgot_password_token) %></a></p>
					<p><strong>Last Reset Request At:</strong> <%= time_ago_in_words(@user.forgot_password_at) %> ago (<%= @user.forgot_password_at %>)</p>
				</div>
			</div>
			<% end %>
		</div>
	</div>
<% end %>

app/views/admin/users/index.html.erb
<div class="table-responsive">
	<h2>Users</h2>
	<table class="table table-striped table-hover">
		<thead>
			<tr>
				<th>Username:</th>
				<th>Status:</th>
				<th>Email:</th>
				<th>Created At:</th>
				<th>Updated At:</th>
			</tr>
		</thead>
		<tbody>
		<% @users.each do |user| %>
			<tr>
				<td><a href="<%= edit_admin_user_path(user) %>"><%= user.display_name %></a></td>
				<td><span class="label label-<%= if user.status == 'active' then 'success' elsif user.status == 'deleted' then 'warning' elsif user.status == 'banned' then 'danger' elsif user.status == 'admin' then 'info' end %>"><%= user.status %></span></td>
				<td><%= user.email %></td>
				<td><%= user.created_at %></td>
				<td><%= user.updated_at %></td>
			</tr>
		<% end %>
		</tbody>
	</table>
</div>