config/routes.rb
Picsite::Application.routes.draw do
  root to: 'homepage#index'
  
  resources :users, only: [:show]
  get    'join' => 'users#new'
  post   'join' => 'users#create'
  get    'settings' => 'users#edit'
  put    'settings' => 'users#update'
    
  get    'changepassword' => 'changepassword#edit',   path: '/settings/changepassword'
  put    'changepassword' => 'changepassword#update', path: '/settings/changepassword'
  
  get    'delete_user' => 'delete_user#edit',    path: '/settings/delete'
  delete 'delete_user' => 'delete_user#destroy', path: '/settings/delete'
  
  get    'user_sessions' => 'sessions#index',   path: '/settings/sessions'
  delete 'user_session'  => 'sessions#destroy', path: '/settings/sessions/:id'
  
  get    'signin'  => 'sessions#new'
  post   'signin'  => 'sessions#create'
  match  'signout' => 'sessions#update'
  
  get    'forgotpassword' => 'forgotpassword#edit'
  match  'forgotpassword' => 'forgotpassword#update', via: [:post, :put]
  
  get    'resetpassword' => 'resetpassword#edit',   path: '/resetpassword/:token'
  put    'resetpassword' => 'resetpassword#update', path: '/resetpassword/:token'
  
  namespace :admin do
    root to: 'homepage#index'
    resources :users, only: [:index, :edit, :update] do
      resources :sessions, only: [:index, :destroy]
    end
  end
end

app/views/layouts/application.html.erb
<!doctype html>
<html>
	<head>
		<meta charset="utf-8">
		<meta http-equiv="X-UA-Compatible" content="IE=edge">
		<title><%= "#{@title} | " if @title.present? %>PicSite</title>
		<meta name="viewport" content="width=device-width, initial-scale=1">
		<%= csrf_meta_tags %>
		<link rel="stylesheet" href="<%= asset_path 'application.css' %>">
		<script src="//ajax.googleapis.com/ajax/libs/jquery/1.11.2/jquery.min.js"></script>
		<script>window.jQuery || document.write('<script src="<%= asset_path 'jquery-1.11.2.js' %>"><\/script>')</script>
		<script src="<%= asset_path 'application.js' %>"></script>
	</head>
	<body>
		<div class="header">
			<div class="container">
				<a class="brand" href="<%= root_path %>">Pic<span>Site</span></a>
				<a href="#" class="header-nav-toggle pull-right"><span class="icon-bar"></span><span class="icon-bar"></span><span class="icon-bar"></span></a>
				<div class="header-nav-container pull-right">
					<ul class="nav header-nav">
					<% if signed_in? %>
						<li><a href="<%= user_path(get_username) %>">Profile</a></li>
						<li><a href="<%= settings_path %>">Settings</a></li>
						<li><a href="<%= signout_path %>">Sign Out</a></li>
					<% else %>
						<li><a href="<%= join_path %>">Join</a></li>
						<li><a href="<%= signin_path %>">Sign In</a></li>
					<% end %>
					</ul>
				</div>
				<script>
				(function($) {
					$('.header-nav-toggle').on('click', function(e) {
						e.preventDefault();
						$(this).parent().find('.header-nav').toggleClass('in');
					});
				})(jQuery);
				</script>
			</div>
		</div>
		<div class="container">
			<%= yield %>
		</div>
	</body>
</html>